In [1]:
from ludwig import LudwigModel
import pandas as pd

In [48]:
ludwig_columns = ['No', 'type', 'area_name', 'area_code', 'states', 'city', 'district', 'closest_station',
       'closest_station_distance', 'value', 'price_per_of_area', 'floor_plan', 'area', 'transaction_price', 'shape',
       'frontage', 'total_floor_area', 'year_of_construction', 'construction', 'use', 'future_use_purpose', 'orientation_front_road', 'type_front_road',
       'road_width', 'city_planning', 'building_coverage', 'floor_area_ratio', 'time_of_transaction', 'renovation', 'transaction_circumstances']

In [49]:
train_df = pd.read_csv('32_Shimane Prefecture_20171_20182.csv', names=ludwig_columns, header=0, index_col="No")
test_df = pd.read_csv('32_Shimane Prefecture_20183_20183.csv', names=ludwig_columns, header=0, index_col="No")
train_df.columns

Index(['type', 'area_name', 'area_code', 'states', 'city', 'district',
       'closest_station', 'closest_station_distance', 'value',
       'price_per_of_area', 'floor_plan', 'area', 'transaction_price', 'shape',
       'frontage', 'total_floor_area', 'year_of_construction', 'construction',
       'use', 'future_use_purpose', 'orientation_front_road',
       'type_front_road', 'road_width', 'city_planning', 'building_coverage',
       'floor_area_ratio', 'time_of_transaction', 'renovation',
       'transaction_circumstances'],
      dtype='object')

In [53]:
train_df.to_csv('shimane_train_en.csv')
test_df.to_csv('shimane_test_en.csv')

In [63]:
model_definition ={
    "input_features": [
        {"name": "type", "type": "category"},
        {"name": "area_name", "type": "category"},
        {"name": "area_code", "type": "category"},
        {"name": "closest_station", "type": "category"},
        {"name": "future_use_purpose", "type": "category"},
        {"name": "building_coverage", "type": "numerical"},
        {"name": "road_width", "type": "numerical"},
        {"name": "renovation", "type": "category"},
    ],
    "output_features": [{"name": "value", "type": "numerical"}],
}

In [65]:
model = LudwigModel(model_definition)

In [66]:
train_stats = model.train(train_df)

/home/regonn/.local/share/virtualenvs/regonn-667eHjES/lib/python3.7/site-packages/ludwig/features/numerical_feature.py:63: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  np.float32).as_matrix()

In [67]:
predictions = model.predict(test_df)

In [68]:
predictions

     value_predictions
0          3931.013428
1          3635.866943
2          4076.049316
3          3796.274170
4          3655.169434
5          3940.964600
6          4303.542480
7          4383.542480
8          3590.837891
9          2154.706543
10         2154.706543
11         2154.706543
12         3905.192871
13         3865.737305
14         2171.009766
15         4188.553223
16         3953.523926
17         3951.818848
18         3951.818848
19         3889.525879
20         3889.525879
21         3889.525879
22         3911.560791
23         3951.818848
24         3688.860596
25         3688.860596
26         3825.969727
27         3917.651855
28         3865.606934
29         4427.525391
..                 ...
281        1892.485596
282        4054.593262
283        4303.426270
284        1877.539185
285        1864.119507
286        1864.119507
287        1836.013916
288        1926.755615
289        2107.909668
290        1926.755615
291        2124.358887
292        1926.755615
293        1995.335449
294        1841.537476
295        1841.537476
296        3067.611572
297        1945.765625
298        1924.002197
299        1920.509399
300        1945.462524
301        1904.206055
302        1904.206055
303        1904.206055
304        2228.124756
305        1944.962891
306        3964.917969
307        3943.440186
308        3918.291992
309        4036.827148
310        3906.635742

[311 rows x 1 columns]